spring:
  application:
    name: spring-cloud-eurake-server
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    fetch-registry: false
    register-with-eureka: false