spring:
  application:
    name: spring-cloud-zuul
server:
  port: 8006
zuul:
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: SPRING-CLOUD-SERVICE-CONSUMER-RIBBON
    feign:
      path: /feign/**
      serviceId: SPRING-CLOUD-SERVICE-CONSUMER-FEIGN
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/